openapi: 3.0.0
paths:
  /users:
    get:
      summary: Get users API   # â† add one word
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
          description: Maximum number of users to return
#
